### ISSUE TITLE
Unable to run demo

### ISSUE THREAD

**Issue by lbzr004** [hfshr/qbr#2]
Hi, I am trying to run the demo but seems that there are extra unexpected characters in there - "|>"

![image](https://user-images.githubusercontent.com/94621653/181936827-0b873eb4-1320-4b23-ac50-66acf7da90fd.png)

**Comment by hfshr** [comment]
Hi, sorry about that. These are the base R pipe operators from R version 4.1 and above, so if you update to R 4.1 or greater then the demo should work. I should probably add a note about the min R version required or just import the usual pipes from magrittr for the demo (note to self!)

**Comment by hfshr** [comment]
Fixed with #3

**Comment by lbzr004** [comment]
Thank you for sharing! I will upgrade the R version.
