### ISSUE TITLE
is_na and is_not_na operators not working

### ISSUE THREAD

**Issue by brucosper** [hfshr/qbr#4]
It seems these operators don't show up in the dropdown, even in the [demo](https://harryfish.shinyapps.io/qbr_demo/). 
I see they're defined in the code (at least in helpers.R) so I assume it's a bug.

**Comment by hfshr** [comment]
Hi, good spot. Looks like I need to add these operators on the JS side as they aren't supported by default like all the others (https://querybuilder.js.org/#operators). I'll look into this :+1:

**Comment by hfshr** [comment]
Fixed with #5
