### ISSUE TITLE
Unable to add additional conditions with queryBuilderInput?

### ISSUE THREAD

**Issue by rmgpanw** [hfshr/qbr#6]
Hi, I was trying to add a 'NOT' condition to `queryBuilderInput()`. While this does show on the UI, it doesn't seem to register if 'NOT' is actually selected, where as 'AND' and 'OR' work as expected (example code below). 

My motivation is use `input$qb$rules` (rather than the R/SQL versions) to generate custom code (e.g. convert to [dplyr set ops](https://dplyr.tidyverse.org/reference/setops.html), 'AND' -> `dplyr::intersect()`, 'OR' -> `dplyr::union()`, 'NOT' -> `dplyr::setdiff()`)

I'd be grateful for your advice, thanks!

```
library(shiny)
library(qbr)

ui <- fluidPage(
  useQueryBuilder(),
  queryBuilderInput(
    inputId = "qb",
    filters = list(list(
      id = "name",
      title = "Name",
      type = "string"
    )),
    conditions = c("AND", "OR", "NOT"),
    return_value = "all"
  ),
  textOutput("rules")
)

server <- function(input, output) {
  observe({
    lobstr::tree(input$qb$rules)
  })
}

shinyApp(ui, server)
```

**Comment by hfshr** [comment]
Hi,  you might be able to get away with using the 'not-group' plugin like so:

```
ui <- fluidPage(
  useQueryBuilder(),
  queryBuilderInput(
    inputId = "qb",
    plugins = list(
      "not-group" = NULL
    ),
    filters = list(list(
      id = "name",
      title = "Name",
      type = "string"
    )),
    conditions = c("AND", "OR"),
    return_value = "all"
  ),
  textOutput("rules")
)

server <- function(input, output) {
  observe({
    print(input$qb$rules)
  })
}

shinyApp(ui, server)

```

You can see a demo of it in action here: https://querybuilder.js.org/demo.html#plugins

Would that give you what you need? If not (no pun intended) I'll see if we can add better support for other conditions.

**Comment by hfshr** [comment]
Actually, this might work better - if you set the return value to "rules" you will get the "NOT" condition in the same way you get "AND" and "OR".

```
ui <- fluidPage(
  useQueryBuilder(),
  queryBuilderInput(
    inputId = "qb",
    filters = list(list(
      id = "name",
      title = "Name",
      type = "string"
    )),
    conditions = c("AND", "OR", "NOT"),
    return_value = "rules"
  ),
  textOutput("rules")
)

server <- function(input, output) {
  observe({
    print(input$qb)
  })
}

shinyApp(ui, server)

```
Your example was using return_type = "all", which meant it was trying to parse the NOT condition for SQL / R rules which has not been implemented. Hopefully this approach will give you what you need

**Comment by rmgpanw** [comment]
These are both great solutions, thank you! Please do consider making this package available on CRAN at some point also 👍
