### ISSUE TITLE
Change name of package to avoid conflict with CRAN pkg

### ISSUE THREAD

**Issue by gabrielb4** [hfshr/qbr#7]
Hi @hfshr,

I'm wondering if you would consider changing the name in the DESCRIPTION File for this package, as there is a currently published CRAN package called 'qbr' which is causing disruption and confusion as we try to use this package in an internal shiny app. 

Perhaps `jqbr`?

Thanks.

**Comment by hfshr** [comment]
Yeah I don't see why that would be a problem. I was going to try and get this submitted to CRAN in the not too distant future so would need to address the package name clash anyway. I like `jqbr` too, thanks for the suggestion @gabrielb4 :+1:

**Comment by hfshr** [comment]
@gabrielb4 now renamed to `jqbr` - will hopefully submit to CRAN in next few days
